### PR TITLE
build(ffmpeg): update to FFmpeg 7.1

### PR DESCRIPTION
**Pull request by cgutman**
## Description
This PR rebases from FFmpeg 6.1 to FFmpeg 7.1.

Notable changes:
- A replacement for `01-amf-colorspace-v3.patch` was upstreamed in FFmpeg 7.1, but it requires a fixup to pass-through the proper colorspace into the bitstream for HEVC and AV1. I replaced it with the patch I sent to ffmpeg-devel, but upstream will probably take [a better fix](https://ffmpeg.org/pipermail/ffmpeg-devel/2024-September/333271.html) that handles both internal RGB->YUV conversion and pre-converted YUV input
- A replacement for `02-idr-on-amf.patch` was upstreamed but missed the 7.1 cut, so this patch is replaced with my upstreamed version. **This requires changes on the Sunshine side to set the `forced_idr` option for AMF like we do for QSV and NVENC.**
- A replacement for `05-amfenc-new-av1-usages.patch` was upstreamed for FFmpeg 7.1, so that patch is dropped completely
- Some minor changes were required to the CBS stuff to adapt to the new VP8 CBS support in FFmpeg 7.1 and the relocation of HEVC-related headers
- `05-vaapi-customized-surface-alignment.patch` needed to be reworked due to upstream refactoring of common VAAPI/D3D12VA/Vulkan encoding logic into a single base class

Testing checklist:
- [x] Software
- [x] QSV
- [x] NVENC (Linux)
- [x] AMF
- [x] VideoToolbox
- [x] VAAPI (Intel)
- [x] VAAPI (AMD + alignment fix)

### Issues Fixed or Closed

- Closes #357 

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Dependency update (updates to dependencies)
- [ ] Documentation update (changes to documentation)
- [ ] Repository update (changes to repository files, e.g. `.github/...`)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the in code docstring/documentation-blocks for new or existing methods/components

### CODE REVIEW

**Review by ReenigneArcher — APPROVED** [review]

**Comment by cgutman** [comment]
OK, I'm not sure why the behavior changed in FFmpeg, but it looks like setting `surfaces=1` for NVENC solves it.

This is ready for merge. I'll open up the Sunshine PR after merge to update the submodule and add the new options for NVENC and AMF.

**Comment by DistantThunder** [comment]
I don't know if it's of any incidence but FFMPEG release/7.1 branch isn't at the same commit as actual tag release 

* https://github.com/FFmpeg/FFmpeg/releases/tag/n7.1

**Comment by ReenigneArcher** [comment]
@DistantThunder we are following the `release/7.1` branch: https://github.com/FFmpeg/FFmpeg/commits/release/7.1/

**Comment by moi952** [comment]
Hi,
What does FFmpeg 7.1 bring to the use of sunshine?
I saw that vulkan had been implemented but not for encoding is that right?
Thanks and sorry for the inconvenience

**Comment by ReenigneArcher** [comment]
The notes in this PR should help answer that: https://github.com/LizardByte/build-deps/pull/359

**Pull request merged**
